### ISSUE TITLE
Swap Bluebird for Promise

### ISSUE THREAD

**Issue by ForbesLindesay** [jstransformers/jstransformer-html2jade#2]
Standards compliance yada yada yada

**Comment by tunnckoCore** [comment]
Slow standards? Bluebird is absolutely awesome and fast. It is Promises A+ implementation as I know. 
It just have more things than Promise Spec, which actually we not use, so it's no matter that we use bluebird. We use it's speed.

Speed is matter in transformers and template engines.

**Comment by TimothyGu** [comment]
See also https://github.com/jstransformers/jstransformer-toml/issues/1#issuecomment-89860737

**Comment by RobLoach** [comment]
Can we get rid of using any Promise wrapper at all yet? Who uses node 0.10 anymore?

**Comment by ForbesLindesay** [comment]
In my benchmarking then/promise is marginally faster than bluebird.  It's also standards compliant where bluebird flouts the es6 standard and has numerous extensions like `.spread` that can easily make your code into a mess of spaghetti that does not do what it looks like it does.

**Comment by ForbesLindesay** [comment]
P.S. Facebook recently switched from bluebird to promise for these reasons.

I think it's still a touch early to drop 0.10 support, but we could consider it.

**Comment by RobLoach** [comment]
PR
